In [1]:
import numpy as np
a= np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
import numpy as np
a= np.array([1,2,3])
b= np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [4]:
b[1]=10

In [5]:
b

array([ 4, 10,  6])

In [6]:
a[0]=11
print(a)

[11  2  3]


In [9]:
c=np.array([[2,3,4],[7,8,9]])
print(c)

[[2 3 4]
 [7 8 9]]


In [10]:
c(0)

TypeError: 'numpy.ndarray' object is not callable

In [11]:
c[0]

array([2, 3, 4])

In [12]:
c[1]

array([7, 8, 9])

In [13]:
c[0:]

array([[2, 3, 4],
       [7, 8, 9]])

In [14]:
c[:1]

array([[2, 3, 4]])

In [15]:
#one direction
a[1]

2

In [16]:
#one direction
a[1:2]

array([2])

In [17]:
c[0:0]

array([], shape=(0, 3), dtype=int32)

In [18]:
c[0:1]

array([[2, 3, 4]])

In [19]:
#one direction
a[1:3]

array([2, 3])

In [20]:
type(a)

numpy.ndarray

In [21]:
type(b)

numpy.ndarray

In [22]:
type(c)

numpy.ndarray

In [25]:
a=np.zeros([3,4])
#np.zeros([rows,col])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
a=np.arange(10,25,5)
#np.arange(start, end, interval)
print(a)

[10 15 20]


In [29]:
a=np.arange(10,19,5)
#np.arange(start, end, interval)
print(a)

[10 15]


In [32]:
b=np.linspace(6,7,5)
#np.linspace(start,end,number of points)
print(b)

[6.   6.25 6.5  6.75 7.  ]


In [33]:
b=np.linspace(6,7,10)
#np.linspace(start,end,number of points)
print(b)

[6.         6.11111111 6.22222222 6.33333333 6.44444444 6.55555556
 6.66666667 6.77777778 6.88888889 7.        ]


In [34]:
b=np.linspace(6,8,10)
#np.linspace(start,end,number of points)
print(b)

[6.         6.22222222 6.44444444 6.66666667 6.88888889 7.11111111
 7.33333333 7.55555556 7.77777778 8.        ]


In [36]:
import numpy as np
#c=np.full((row,col),number)
c=np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [37]:
import numpy as np
#c=np.full((row,col),number)
c=np.full((2,4),7)
print(c)

[[7 7 7 7]
 [7 7 7 7]]


In [38]:
c[0:0]

array([], shape=(0, 4), dtype=int32)

In [39]:
c[0:1]

array([[7, 7, 7, 7]])

In [41]:
import numpy as np
d=np.random.random((3,4))
print(d)

[[0.79781333 0.23709174 0.79854276 0.15540492]
 [0.69210993 0.19838754 0.38017713 0.06091955]
 [0.52540753 0.3345432  0.80606423 0.11851488]]


In [42]:
import numpy as np
d=np.random.random((3,4))
print(d)

[[0.64826567 0.90027262 0.67540819 0.51344254]
 [0.78006564 0.70192945 0.31590946 0.41149945]
 [0.24441625 0.63942591 0.98868981 0.42048699]]


In [43]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [44]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [49]:
a.shape=(3,2)
print(a)
print(a.shape)
#change row and com

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [55]:
a.shape=(3,2)
print(a)
print(a.shape[0])
#returns row number

[[1 2]
 [3 4]
 [5 6]]
3


In [52]:
a.shape=(3,2)
print(a)
print(a.shape[0:2])
#returns row number

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [56]:
a=np.arange(24)

In [57]:
a.size

24

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [61]:
#np.arange(number) prints from 0 to that number
b=np.arange(10)
print(b.size)
print(b)

10
[0 1 2 3 4 5 6 7 8 9]


In [67]:
import numpy as np
d=np.array([[1,2,3],[4,5,6]])
print(d.shape)
print(d.shape[0])
#print row
print(d.shape[1])
#prints col
print(d.ndim)
#prints dimension
print(d)

(2, 3)
2
3
2
[[1 2 3]
 [4 5 6]]


In [68]:
d.dtype

dtype('int32')

In [69]:
a=np.linspace(4,5,5)
print(a)
print(a.dtype)

[4.   4.25 4.5  4.75 5.  ]
float64


In [70]:
import numpy as np
a=np.array([1,3])
print(np.sum(a))

4


In [72]:
import numpy as np
a=np.array([[1,3],[1,1]])
print(np.sum(a))

6


In [94]:
import numpy as np
a=np.array([[0,1],[0,5]], axis=0)
print(a)

TypeError: 'axis' is an invalid keyword argument for array()

In [82]:
import numpy as np
a=np.sum([[1,3],[1,2],[1,4]], axis=0)
print(a)

[3 9]


In [75]:
a

array([2, 4])

In [80]:
import numpy as np
a=np.sum([[0,3],[5,1]], axis=1)
print(a)

[3 6]


In [90]:
import numpy as np
a=np.subtract(2,3)
print(a)

-1


In [92]:
import numpy as np
a=np.subtract(3,3)
print(a)

0


In [95]:
import numpy as np
a=np.divide(6,2)
print(a)

3.0


In [102]:
import numpy as np
b=np.array([6,3])
c=np.array([2,1])
a=np.divide(b,c)
print(b)
print(c)
print(a)

[6 3]
[2 1]
[3. 3.]


In [107]:
b=np.array([6,3])
c=np.array([2,2])
a=np.multiply(b,c)
print(a)

[12  6]


In [110]:
a=np.multiply(2,2)
print(a)

4


In [112]:
a=np.sqrt(25)
print(a)

5.0


In [113]:
a=np.exp(2)
print(a)

7.38905609893065


In [114]:
print(np.cos(30))

0.15425144988758405


In [115]:
print(np.log(2))

0.6931471805599453


In [1]:
import numpy as np
a=[1,2,3]
b=[1,2,7]
print(np.equal(a,b))

[ True  True False]


In [2]:
import numpy as np
a=[1,2,3]
b=[1,1,7]
print(np.equal(a,b))

[ True False False]


In [4]:
import numpy as np
a=[1,2,3]
b=[1,2,7]
print(np.array_equal(a,b))

False


In [5]:
import numpy as np
a=[1,2,3]
b=[1,2,3]
print(np.array_equal(a,b))

True


In [6]:
import numpy as np
a=[1,2,3]
print(sum(a))
print(min(a))

6
1


In [13]:
a=np.sqrt(2)
print(a)

1.4142135623730951


In [7]:
import numpy as np
a=[1,2,3]
print(np.sum(a))
print(np.min(a))
print(np.max(a))

6
1
3


In [17]:
import numpy as np
a=[1,2,3]
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.corrcoef(a))

6
2.0
2.0
0.816496580927726
1.0


In [22]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,1,1])
c=np.sum([a,b])
print(a)
print(b)
print('After adding')
print(c)

[[1 2 3]
 [4 5 6]]
[1 1 1]
After adding
[[2 3 4]
 [5 6 7]]


In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,1,1])
c=np.sum([a,b])
print(a)
print(b)
print('After adding')
#print(c)

ValueError: could not broadcast input array from shape (3,3) into shape (3)

In [29]:
a=np.array([[1,2,3],[2,3,4],[4,5,6],[5,6,7],[6,7,8],[7,8,9]])
b=np.array([1,1,1])
print(np.sum([a,b]))

[[ 2  3  4]
 [ 3  4  5]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [30]:
a=np.array([[1,2,3],[2,3,4],[4,5,6],[5,6,7],[6,7,8],[7,8,9]])
b=np.array([1,1,1])
print(np.subtract(a,b))

[[0 1 2]
 [1 2 3]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


In [31]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])
b=np.array([1,1,1])
print(np.subtract(a,b))

[[0 1 2]
 [1 2 3]
 [3 4 5]]


In [33]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])
b=np.array([1,1,1])
print(np.sum([a,b]))

ValueError: could not broadcast input array from shape (3,3) into shape (3)