In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('first row')
print(a[0])

first row
[1 2 3]


In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('second row')
print(a[1])

second row
[4 5 6]


In [23]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(' upto first row')
print(a[:1])

 upto first row
[[1 2 3]]


In [13]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('upto that row')
print(a[:2])

upto that row
[[1 2 3]
 [4 5 6]]


In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('upto that row and col')
print(a[:1,:1])

upto that row and col
[[1]]


In [19]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('upto that row and col')
print(a[:1,:2])

upto that row and col
[[1 2]]


In [16]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('first row')
print(a[:2,:1])

first row
[[1]
 [4]]


In [22]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('upto row and col')
print(a[:2,:0])

upto row and col
[]


In [24]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('from row and upto col')
print(a[2:,:3])

from row and upto col
[[7 8 9]]


In [27]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[:2,2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]]


In [28]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[:1,2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]]


In [38]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
c=np.concatenate([a,b])
print('one dimension array')
print(c)

[1 2 3]
[4 5 6]
one dimension array
[1 2 3 4 5 6]


In [33]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print(b)
c=np.concatenate([a,b])
print('two dimension array')
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
two dimension array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print(b)
c=np.concatenate([a,b], axis=0)
print('two dimension array axis=0 means row wise')
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
two dimension array axis=0 means row wise
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print(b)
c=np.concatenate([a,b], axis=1)
print('two dimension array axis=1 means col wise')
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
two dimension array axis=1 means col wise
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [39]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b), axis=0)
print(c)

[[1 2 3]
 [4 5 6]]


In [41]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b), axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [44]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print('Matrix a')
print(a)
print('Matrix b')
print(b)
print('horizontal stack')
print(np.hstack((a,b)))
print('vertical stack')
print(np.vstack((a,b)))

Matrix a
[[1 2 3]
 [4 5 6]]
Matrix b
[[ 7  8  9]
 [10 11 12]]
horizontal stack
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
vertical stack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print('Matrix a')
print(a)
print('Matrix b')
print(b)
print('horizontal stack')
print(np.hstack((a,b)))
print('horizontal concatenate')
print(np.concatenate((a,b),axis=0))
print('vertical stack')
print(np.vstack((a,b)))
print('vertical concatenate')
print(np.concatenate((a,b),axis=1))

Matrix a
[[1 2 3]
 [4 5 6]]
Matrix b
[[ 7  8  9]
 [10 11 12]]
horizontal stack
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
horizontal concatenate
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vertical stack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vertical concatenate
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [45]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print('Matrix a')
print(a)
print('Matrix b')
print(b)
print('horizontal stack')
print(np.hstack((a,b)))
print('horizontal concatenate')
print(np.concatenate((a,b),axis=0))
print('vertical stack')
print(np.vstack((a,b)))
print('vertical concatenate')
print(np.concatenate((a,b),axis=1))
print('Column stack')
print(np.column_stack((a,b)))

Matrix a
[[1 2 3]
 [4 5 6]]
Matrix b
[[ 7  8  9]
 [10 11 12]]
horizontal stack
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
horizontal concatenate
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vertical stack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vertical concatenate
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Column stack
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('after spliting')
print(np.split(a,2,axis=0))

[[1 2 3]
 [4 5 6]]
after spliting
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('after spliting')
print(np.split(a,3,axis=1))

[[1 2 3]
 [4 5 6]]
after spliting
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('after spliting')
print(np.split(a,[1,2],axis=1))

[[1 2 3]
 [4 5 6]]
after spliting
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [9]:
a[:,:1]

array([[1],
       [4]])

In [10]:
a[:,:2]

array([[1, 2],
       [4, 5]])

In [11]:
a[:,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a[1:,:2]

array([[4, 5]])